/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transportation;

import java.lang.NullPointerException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import voguetexmachinesharing.managementsystem.*;

/**
 *
 * @author Dasuni Anupama
 */
public class TransportationModuleMainMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeTransport
     */
    public TransportationModuleMainMenu() {
        initComponents();
        clearFieldsEmpTransport();
        populateEmpTransportTable();
        populateDDStyleNo();
        clearFieldsvehicle();
        populatevehicleTable();
        clearFieldsassingdriver();
        populateassingdriverTable();

    }

    ArrayList<Emp> Emplist;
    ArrayList<Vehicle> Vehiclelist;
    ArrayList<AssingDriver> driverlist;

    Emp emp = new Emp();
    DBOperationTransportation dbOpe = new DBOperationTransportation();

    Vehicle v = new Vehicle();
    DBOperationTransportation dbOpv = new DBOperationTransportation();

    AssingDriver asg = new AssingDriver();
    DBOperationTransportation dbOpdr = new DBOperationTransportation();

    void clearFieldsEmpTransport() {
//        e_route.getSelectedItem("select one");

    }

    void populateEmpTransportTable() {
        Emplist = dbOpe.getEmpT();
        EmpTransportDetails finalModel = new EmpTransportDetails(Emplist);
        empTransport_table.setModel(finalModel);
    }

    void clearFieldsvehicle() {
        vNumTxt.setText("");
        //((JTextField)jDateChooser6.getDateEditor().getUiComponent()).setText(" ");
    }

    void populatevehicleTable() {
        Vehiclelist = dbOpv.getvehicle();
        VehicleDetails finalModel = new VehicleDetails(Vehiclelist);
        reg_table.setModel(finalModel);

    }

    void clearFieldsassingdriver() {
        dName.setText("");
        dNIC.setText("");
        ((JTextField) d_dob.getDateEditor().getUiComponent()).setText(" ");
        genderCB.setSelectedItem("select one");
        vTypeCB2.setSelectedItem("select one");
    }

    void populateassingdriverTable() {
        driverlist = dbOpdr.getAssingDriver();
        AssignDriverDetails finalModel = new AssignDriverDetails(driverlist);
        asg_table.setModel(finalModel);

    }

    public static boolean checkNIC(String nic) {
        //System.out.println("kkkkkkk: " + nic.charAt(9));
        if ((nic.length() == 10)) //&& (nic.charAt(9) == 'V' || nic.charAt(9)=='v') && (nic.matches("/^[0-9]{9}[vVxX]$/")))
        {
            if ((nic.charAt(9) == 'V') || (nic.charAt(9) == 'v')) {
                if (nic.trim().matches("^[0-9]{9}[vVxX]$")) {
                    return true;
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    void populateDDStyleNo() {
        Vehiclelist = dbOpv.getvehicle();
        String[] arr = new String[Vehiclelist.size()];
        for (int i = 0; i < Vehiclelist.size(); i++) {
            arr[i] = Vehiclelist.get(i).getType();
        }
        for (int i = 0; i < Vehiclelist.size(); i++) {
            // dLicenseCB.addItem(arr[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vNumTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        vTypeCB = new javax.swing.JComboBox<>();
        vCapacityCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        routeCB = new javax.swing.JComboBox<>();
        vRegButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reg_table = new javax.swing.JTable();
        reg_update = new javax.swing.JButton();
        reg_delete = new javax.swing.JButton();
        demo_vehiReg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dNIC = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        dName = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        vTypeCB2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        d_dob = new com.toedter.calendar.JDateChooser();
        genderCB = new javax.swing.JComboBox<>();
        vehNumCB = new javax.swing.JComboBox<>();
        driver_submit = new javax.swing.JButton();
        driver_update = new javax.swing.JButton();
        driver_delete = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        asg_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vtype = new javax.swing.JComboBox<>();
        e_route = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        VCapacityCB2 = new javax.swing.JComboBox<>();
        SeatsRequired = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emp_submit = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        empTransport_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Transportation Management ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jLabel20.setText("Vehicle Number");

        jLabel21.setText("Vehicle Type");

        vNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNumTxtActionPerformed(evt);
            }
        });
        vNumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vNumTxtKeyTyped(evt);
            }
        });

        jLabel29.setText("Capacity");

        vTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select one", "Bus", "Lorry" }));
        vTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vTypeCBActionPerformed(evt);
            }
        });

        jLabel10.setText("Route");

        routeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select one", "Route A", "Route B", "Route C" }));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel29)
                    .addComponent(jLabel10))
                .addGap(76, 76, 76)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vNumTxt)
                    .addComponent(vTypeCB, 0, 129, Short.MAX_VALUE)
                    .addComponent(vCapacityCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(routeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(vNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(vTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(vCapacityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(routeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        vRegButton.setText("Submit");
        vRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vRegButtonActionPerformed(evt);
            }
        });

        reg_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Vehicle Type", "Capacity", "Route", "Driver Assigned", "Available Capacity"
            }
        ));
        reg_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(reg_table);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        reg_update.setText("Update");
        reg_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_updateActionPerformed(evt);
            }
        });

        reg_delete.setText("Delete");
        reg_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_deleteActionPerformed(evt);
            }
        });

        demo_vehiReg.setText("Demo");
        demo_vehiReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demo_vehiRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(vRegButton)
                        .addGap(140, 140, 140)
                        .addComponent(demo_vehiReg))
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(reg_update)
                        .addGap(145, 145, 145)
                        .addComponent(reg_delete))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(demo_vehiReg)
                    .addComponent(vRegButton)
                    .addComponent(reg_update)
                    .addComponent(reg_delete))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehicle Registration", jPanel8);

        jLabel24.setText("Driver Name");

        jLabel28.setText("Vehicle Type");

        dNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNICActionPerformed(evt);
            }
        });
        dNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dNICKeyTyped(evt);
            }
        });

        jLabel31.setText("Driver NIC");

        dName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dNameKeyTyped(evt);
            }
        });

        jLabel33.setText("Vehicle Number");

        vTypeCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select one", "Bus", "Lorry" }));
        vTypeCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vTypeCB2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Date of Birth");

        jLabel5.setText("Gender");

        d_dob.setDateFormatString("dd-MM-yyy");

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select one", "Male", "Female" }));
        genderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCBActionPerformed(evt);
            }
        });

        vehNumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehNumCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genderCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(vTypeCB2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vehNumCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel31))
                        .addGap(134, 134, 134)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(dName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(39, 39, 39)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(d_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(vTypeCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(vehNumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        driver_submit.setText("Submit");
        driver_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_submitActionPerformed(evt);
            }
        });

        driver_update.setText("Update");
        driver_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_updateActionPerformed(evt);
            }
        });

        driver_delete.setText("Delete");
        driver_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_deleteActionPerformed(evt);
            }
        });

        asg_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Driver Name", "Driver NIC", "Date of Birth", "Gender", "Vehicle Type", "Vehicle Number"
            }
        ));
        asg_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asg_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(asg_table);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jButton2)
                        .addGap(113, 113, 113)
                        .addComponent(driver_submit)
                        .addGap(140, 140, 140)
                        .addComponent(driver_update)
                        .addGap(136, 136, 136)
                        .addComponent(driver_delete)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driver_submit)
                            .addComponent(driver_update)
                            .addComponent(driver_delete)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assign Driver", jPanel3);

        jLabel3.setText("Vehicle Number");

        jLabel4.setText("Route ");

        vtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtypeActionPerformed(evt);
            }
        });

        e_route.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select one", "Route A", "Route B", "Route C" }));
        e_route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_routeActionPerformed(evt);
            }
        });

        jLabel12.setText("Vehicle Capacity");

        VCapacityCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VCapacityCB2ActionPerformed(evt);
            }
        });

        SeatsRequired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsRequiredActionPerformed(evt);
            }
        });

        jLabel9.setText("No of Seats Required ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(e_route, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VCapacityCB2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 121, Short.MAX_VALUE)
                            .addComponent(vtype, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(151, 151, 151)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeatsRequired, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(e_route, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VCapacityCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(42, 42, 42)
                        .addComponent(vtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeatsRequired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        emp_submit.setText("Submit");
        emp_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_submitActionPerformed(evt);
            }
        });

        empTransport_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Route", "Employee Count"
            }
        ));
        jScrollPane6.setViewportView(empTransport_table);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(emp_submit)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(emp_submit)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employee Transportation", jPanel2);

        jButton1.setText("Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Assign Driver Report");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(901, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asg_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asg_tableMouseClicked
        // TODO add your handling code here:

        try {

            AssingDriver ao = driverlist.get(asg_table.getSelectedRow());

            dName.setText(ao.getDriverName());
            dNIC.setText(ao.getDriverNIC());
            java.util.Date dob = new SimpleDateFormat("dd-MM-yyyy").parse(ao.getDob());

          
            d_dob.setDate(dob);
            genderCB.setSelectedItem(ao.getGender());
           
            
            if (ao.getVehicleNumber() != null) {
                vehNumCB.setSelectedItem(ao.getVehicleNumber());
            }
            if (ao.getVehicleType() != null) {
                vTypeCB2.setSelectedItem(ao.getVehicleType());
            }

            dName.setEnabled(false);
            dNIC.setEnabled(false);
            d_dob.setEnabled(false);
            
            genderCB.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException e) {

            JOptionPane.showMessageDialog(this, "Select a row to Assign!!!");

        } catch (ParseException ex) {
            Logger.getLogger(TransportationModuleMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_asg_tableMouseClicked

    private void driver_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_deleteActionPerformed
        // TODO add your handling code here:

        System.out.println("Vehicle ");
        String nicNum = dNIC.getText();
        String vehicleNum = vehNumCB.getSelectedItem().toString();
        if (dbOpdr.DeleteAssignDriver(nicNum)) {
            populateassingdriverTable();
            JOptionPane.showMessageDialog(this, "Successfully Deleted Record!!!");
            clearFieldsassingdriver();
        } else {
            JOptionPane.showMessageDialog(this, "Error While Deleting!!! Please Select A record to delete");
        }

    }//GEN-LAST:event_driver_deleteActionPerformed

    private void driver_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_updateActionPerformed
        // TODO add your handling code here:

        if (dNIC.getText().equals("") || vehNumCB.getSelectedItem().equals("select one") || vehNumCB.getSelectedItem() == "" || vehNumCB.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(this, "Please Fill required Fields !!!");
        } else {

            asg.setDriverName(dName.getText());
            asg.setDriverNIC(dNIC.getText());
            asg.setDob(((JTextField) d_dob.getDateEditor().getUiComponent()).getText());
            asg.setGender(genderCB.getSelectedItem().toString());
            asg.setVehicleType(vTypeCB2.getSelectedItem().toString());
            asg.setVehicleNumber(vehNumCB.getSelectedItem().toString());

            if (dbOpdr.UpdateAssingDriver(asg, driverlist.get(asg_table.getSelectedRow()))) {
                populateassingdriverTable();
                JOptionPane.showMessageDialog(this, "Data Updated Successfully !!!");
                clearFieldsassingdriver();

            } else {

                JOptionPane.showMessageDialog(this, "Error While Updating !!!");

            }

        }
    }//GEN-LAST:event_driver_updateActionPerformed

    private void driver_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_submitActionPerformed
        // TODO add your handling code here:

        if (dName.getText().equals("") || dNIC.getText().equals("") || d_dob.getDate().equals("") || genderCB.getSelectedItem().equals("select one")) {

            JOptionPane.showMessageDialog(this, "Please Fill All The Fields !!!");

        } else {
            boolean nicVal = checkNIC(dNIC.getText());

            if (nicVal == false) {
                JOptionPane.showMessageDialog(this, "Invalid NIC. Please enter a valid NIC number");
            } else {
                asg.setDriverName(dName.getText());
                asg.setDriverNIC(dNIC.getText());
                asg.setDob(((JTextField) d_dob.getDateEditor().getUiComponent()).getText());
                asg.setGender(genderCB.getSelectedItem().toString());
              
                asg.setVehicleType(vTypeCB2.getSelectedItem().toString());
                asg.setVehicleNumber(vehNumCB.getSelectedItem().toString());

                if (dbOpdr.AddAssingDriver(asg)) {
                    populateassingdriverTable();

                    JOptionPane.showMessageDialog(this, "Data Inserted Successfully !!!");
                    clearFieldsassingdriver();

                } else {

                    JOptionPane.showMessageDialog(this, "Error While Insertion !!!");

                }
            }
        }


    }//GEN-LAST:event_driver_submitActionPerformed

    private void vTypeCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vTypeCB2ActionPerformed
// TODO add your handling code here:
        vehNumCB.removeAllItems();
        String vehicleType = vTypeCB2.getSelectedItem().toString();

        try {
            ResultSet availVehiclesRS = dbOpv.getAvailableVehicles(vehicleType);

            if (!availVehiclesRS.next()) {
                vehNumCB.addItem("select one");
            } else {
                vehNumCB.addItem(availVehiclesRS.getString("vehicle_number"));
            }
 
            availVehiclesRS.close();
        } catch (SQLException ex) {
            Logger.getLogger(TransportationModuleMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vTypeCB2ActionPerformed

    private void demo_vehiRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demo_vehiRegActionPerformed
        // TODO add your handling code here:
        
        vNumTxt.setText("UG-5532");
    }//GEN-LAST:event_demo_vehiRegActionPerformed

    private void reg_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_deleteActionPerformed
        // TODO add your handling code here:

        String vehicleNum = vNumTxt.getText();

        if (dbOpv.deletevehicle(vehicleNum)) {
            populatevehicleTable();
            JOptionPane.showMessageDialog(this, "Successfully Deleted Record!!!");//imported java.swing class
            clearFieldsvehicle();
        } else {
            JOptionPane.showMessageDialog(this, "Error While Deleting!!! Please Select A record to delete");
        }
    }//GEN-LAST:event_reg_deleteActionPerformed

    private void reg_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_updateActionPerformed
        // TODO add your handling code here:

        if (vNumTxt.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Please provide a valid vehicle number !!!");

        } else if (routeCB.getSelectedItem().equals("select one")) {
            JOptionPane.showMessageDialog(this, "Please select a route !!!");
        } else {

            String vehicleNum = vNumTxt.getText();
            String route = routeCB.getSelectedItem().toString();

            if (dbOpv.updateVehicle(vehicleNum, route)) {
                populatevehicleTable();
                JOptionPane.showMessageDialog(this, "Data Updated Successfully !!!");
                clearFieldsvehicle();

            } else {

                JOptionPane.showMessageDialog(this, "Error While Updating !!!");

            }

        }
    }//GEN-LAST:event_reg_updateActionPerformed

    private void vRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vRegButtonActionPerformed
        // TODO add your handling code here:

        if (vNumTxt.getText().equals("") || vTypeCB.getSelectedItem().equals("select one") || routeCB.getSelectedItem().equals("select one") || routeCB.getSelectedItem().equals("select one")) {

            JOptionPane.showMessageDialog(this, "Please provide valid details !!!");

        } else {
            VehicleNumValidation obtVal = new VehicleNumValidation(vNumTxt);
            if (obtVal.isVehicle()) {

                v.setVehicleNUm(vNumTxt.getText());
                v.setType(vTypeCB.getSelectedItem().toString());
                String capacity = vCapacityCB.getSelectedItem().toString();
                v.setRoute(routeCB.getSelectedItem().toString());

                if (capacity.equals("20000 kg")) {
                    v.setCapacity(20000);
                } else if (capacity.equals("12000 kg")) {
                    v.setCapacity(12000);
                } else {
                    v.setCapacity(Integer.parseInt(vCapacityCB.getSelectedItem().toString()));
                }

                if (dbOpv.addvehicle(v)) {
                    populatevehicleTable();
                    JOptionPane.showMessageDialog(this, "Data Inserted Successfully !!!");
                    clearFieldsvehicle();

                } else {

                    JOptionPane.showMessageDialog(this, "Error While Insertion !!!");

                }

            } else {
                JOptionPane.showMessageDialog(this, "Enter valid vehicle number!");
            }
        }
    }//GEN-LAST:event_vRegButtonActionPerformed

    private void vTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vTypeCBActionPerformed
        // TODO add your handling code here:

        vCapacityCB.removeAllItems();

        String vType = vTypeCB.getSelectedItem().toString();
       

        if (vType.equals("Bus")) {
            vCapacityCB.addItem("60");
            vCapacityCB.addItem("40");
            
        } else if (vType.equals("Lorry")) {
            vCapacityCB.addItem("12000 kg");
            vCapacityCB.addItem("20000 kg");
        }

    }//GEN-LAST:event_vTypeCBActionPerformed

    private void vNumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vNumTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_vNumTxtKeyTyped

    private void emp_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_submitActionPerformed
        // TODO add your handling code here:

        if (e_route.getSelectedItem().equals("select one")) {

            JOptionPane.showMessageDialog(this, "Please select a Route !!!");

        } else {
            emp.setRoute(routeCB.getSelectedItem().toString());
            VCapacityCB2.getSelectedItem().toString();
            vtype.getSelectedItem().toString();
            int s = Integer.parseInt(SeatsRequired.getText());
            String num = vtype.getSelectedItem().toString();

            boolean result = dbOpe.getEmployeeTransportDetails(s, num);
            if (result) {
                JOptionPane.showMessageDialog(this, "Data Updated Successfully !!!");
                clearFieldsassingdriver();

            } else {

                JOptionPane.showMessageDialog(this, "Error While Updating !!!");

            }


        }
    }//GEN-LAST:event_emp_submitActionPerformed

    private void vtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vtypeActionPerformed

    private void dNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dNICKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_dNICKeyTyped

    private void reg_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_tableMouseClicked
        // TODO add your handling code here:

        try {

            Vehicle vo = Vehiclelist.get(reg_table.getSelectedRow());

            vNumTxt.setText(vo.getVehicleNUm());
            vTypeCB.setSelectedItem(vo.getType());
            vCapacityCB.setSelectedItem(vo.getCapacity());
            routeCB.setSelectedItem(vo.getRoute());

            vNumTxt.setEnabled(false);
            vTypeCB.setEnabled(false);
            //vCapacityCB.enable(false);
            vCapacityCB.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException e) {

            JOptionPane.showMessageDialog(this, "Select a row to Assign!!!");

        }
    }//GEN-LAST:event_reg_tableMouseClicked

    private void vNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vNumTxtActionPerformed

    private void vehNumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehNumCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehNumCBActionPerformed

    private void VCapacityCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VCapacityCB2ActionPerformed
        // TODO add your handling code here:

        vtype.removeAllItems();
        String route = e_route.getSelectedItem().toString();
        String capacity = VCapacityCB2.getSelectedItem().toString();

        try {
            ResultSet vehNmRS = dbOpv.getVehicleNmsDependingOnSeatings(route, capacity);
            
            while (vehNmRS.next()) {
                vtype.addItem(vehNmRS.getString("vehicle_number"));
            }
            vehNmRS.close();
        } catch (SQLException ex) {
            Logger.getLogger(TransportationModuleMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_VCapacityCB2ActionPerformed

    private void e_routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_routeActionPerformed
        // TODO add your handling code here:
        VCapacityCB2.removeAllItems();
        vtype.removeAllItems();
        String route = e_route.getSelectedItem().toString();

        try {
            ResultSet seatCapRS = dbOpv.getAvailableSeatCapacities(route);
            System.out.println("seatCapRS: ");
            while (seatCapRS.next()) {
                System.out.println("seatCapRS: " + seatCapRS.getString("avalable_capacity"));
                VCapacityCB2.addItem(seatCapRS.getString("avalable_capacity"));
            }
            seatCapRS.close();
        } catch (Exception e) {
            //Logger.getLogger(TransportationModuleMainMenu.class.getName()).log(Level.SEVERE, null, e);

        }


    }//GEN-LAST:event_e_routeActionPerformed

    private void SeatsRequiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsRequiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsRequiredActionPerformed

    private void dNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNICActionPerformed

    private void genderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCBActionPerformed

    private void dNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dNameKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_dNameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        MyReportViewer r = new MyReportViewer("C:\\Users\\Sampath Rajapakse\\Documents\\NetBeansProjects\\VogueTexMachineSharing&ManagementSystem\\ireports\\TransportationModule\\AssignDriver.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        dName.setText("Somadasa Jayasinghe");
        dNIC.setText("684792153V");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SeatsRequired;
    private javax.swing.JComboBox<String> VCapacityCB2;
    private javax.swing.JTable asg_table;
    private javax.swing.JTextField dNIC;
    private javax.swing.JTextField dName;
    private com.toedter.calendar.JDateChooser d_dob;
    private javax.swing.JButton demo_vehiReg;
    private javax.swing.JButton driver_delete;
    private javax.swing.JButton driver_submit;
    private javax.swing.JButton driver_update;
    private javax.swing.JComboBox<String> e_route;
    private javax.swing.JTable empTransport_table;
    private javax.swing.JButton emp_submit;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton reg_delete;
    private javax.swing.JTable reg_table;
    private javax.swing.JButton reg_update;
    private javax.swing.JComboBox<String> routeCB;
    private javax.swing.JComboBox<String> vCapacityCB;
    private javax.swing.JTextField vNumTxt;
    private javax.swing.JButton vRegButton;
    private javax.swing.JComboBox<String> vTypeCB;
    private javax.swing.JComboBox<String> vTypeCB2;
    private javax.swing.JComboBox<String> vehNumCB;
    private javax.swing.JComboBox<String> vtype;
    // End of variables declaration//GEN-END:variables

    private Statement setInt(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Statement setString(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Statement setDate(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
